# Site settings
title: Security for Embedded Systems
email: geoff.nichols@oampsoftware.com
description: > # this means to ignore newlines until "baseurl:"
  Security for Embedded Systems
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://oampsoftware.github.io" # the base hostname & protocol for your site
twitter_username: oampsoftware
github_username:  oampsoftware

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
# theme: jekyll-theme-cayman
collections:
    security:
        pam:
            output: true
        radius:
            output: true
        tacplus:
            output: true
